### ISSUE TITLE
Connect DB with PHP doesn't work

### ISSUE THREAD

**Issue by albertcito** [dmytrotus/wordpress-docker-m1#1]
Hi, I don't know if you are maintaining this repository. But I have a question.

I make it works in this URL : http://localhost:7300/ 
I can connect to the DB though TablePlus

![Screen Shot 2021-12-16 at 5 43 02 PM](https://user-images.githubusercontent.com/1768483/146460077-5e610f8c-9323-4542-afcd-f0c5ad3196a3.png)

But if I try to connect to the DB with PHP code it returns this error: 

> Warning: mysqli::__construct(): (HY000/2002): Connection refused in /var/www/project/public/index.php on line 7
> Connection failed: Connection refused

I'm using this basic code: 

```php
<?php
$servername = "127.0.0.1";
$username = "root";
$password = "root";

// Create connection
$conn = new mysqli($servername, $username, $password);

// Check connection
 if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}
echo "Connected successfully";
?>
```

How can I get this connection to work with PHP code?

**Comment by dmytrotus** [comment]
Hello @albertcito. 
<img width="431" alt="Знімок екрана 2021-12-19 о 17 29 07" src="https://user-images.githubusercontent.com/53098289/146682759-91b647eb-6081-42e4-a2a8-0d621ce82dfc.png">

When you are setting up some technology ( in this case mysql ) inside docker container, there are some difference with ports and hostname.

In the image attached I've added example configuration of mariadb.
So if you want to connect to database inside the container ( it is your case ), you need to write host mariadb and port 3306
Example:
`DB_CONNECTION=mysql`
`DB_HOST=mariadb`
`DB_PORT=3306`
`DB_DATABASE=my_database`
`DB_USERNAME=root`
`DB_PASSWORD=root`

`DB_HOST=mariadb` and NOT `DB_HOST=localhost` because in docker network you have `container_name: mariadb`

But if you want to connect to the database from the another environment ( through sequel pro etc. ), you need to make host  localhost and port 3326 ( look at the line 49 from image )

**Comment by albertcito** [comment]
Perfect, thank you very much for the explanation!
